name: nursurau
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.1.2

  # Image handling
  image_picker: ^1.2.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.3.2

  # UUID for unique device IDs
  uuid: ^4.4.0

  # Charts
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#FFFFFF"          # Background color
  image: assets/logo.png    # Splash logo
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/default_surau.png