// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9eQm63eAYGOIBSwUusIgfc83liEWsJQg',
    appId: '1:779548199598:web:bebcb679324f9305dc7b3f',
    messagingSenderId: '779548199598',
    projectId: 'nursurau2',
    authDomain: 'nursurau2.firebaseapp.com',
    storageBucket: 'nursurau2.firebasestorage.app',
    measurementId: 'G-Z83S775MLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_v-V-BTtBD30pjQOVsKcJ7Chul0VPPvo',
    appId: '1:779548199598:android:77abe3e1581a32a4dc7b3f',
    messagingSenderId: '779548199598',
    projectId: 'nursurau2',
    storageBucket: 'nursurau2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeQi_AwyRWGm0hUhAzpPRAADtTnBCw74',
    appId: '1:779548199598:ios:6387086dba54d07edc7b3f',
    messagingSenderId: '779548199598',
    projectId: 'nursurau2',
    storageBucket: 'nursurau2.firebasestorage.app',
    iosBundleId: 'com.example.nursurau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEeQi_AwyRWGm0hUhAzpPRAADtTnBCw74',
    appId: '1:779548199598:ios:6387086dba54d07edc7b3f',
    messagingSenderId: '779548199598',
    projectId: 'nursurau2',
    storageBucket: 'nursurau2.firebasestorage.app',
    iosBundleId: 'com.example.nursurau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9eQm63eAYGOIBSwUusIgfc83liEWsJQg',
    appId: '1:779548199598:web:d8d42c4436ac3feedc7b3f',
    messagingSenderId: '779548199598',
    projectId: 'nursurau2',
    authDomain: 'nursurau2.firebaseapp.com',
    storageBucket: 'nursurau2.firebasestorage.app',
    measurementId: 'G-0492Y8YZWT',
  );

}